### ISSUE TITLE
To implement a multiple node sets example

### ISSUE THREAD

**Issue by SidneyLann** [joshcarty/tfgnn-ogb#12]
This repo is very useful for me, could you please implement a multiple node sets example. Thanks!

**Comment by joshcarty** [comment]
Thanks, that's great to hear the repository has been useful to you.

I created this example in the absence of examples in [tensorflow/gnn](https://github.com/tensorflow/gnn). There are now official examples so I won't be maintaining or extending this repository.

I hope you understand. Thanks!
